### ISSUE TITLE
Timeout issue?

### ISSUE THREAD

**Issue by ice-fly** [newcomb-luke/ERPL-Bot#2]
**I suspect the discord bot times out and fails because of this...**
"google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')"

<details> 
```

...
Member updated
Updating all members
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 47, in on_member_update
    await self.update_members(before.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Member joined
Updating all members
Member updated
Updating all members
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 39, in on_member_join
    await self.update_members(member.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Member updated
Updating all members
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 47, in on_member_update
    await self.update_members(before.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 47, in on_member_update
    await self.update_members(before.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Member updated
Updating all members
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 47, in on_member_update
    await self.update_members(before.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
Member updated
Updating all members
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 47, in on_member_update
    await self.update_members(before.guild)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\__main__.py", line 58, in update_members
    spreadsheet_members = get_members_from_spreadsheet(google_sheets, SPREADSHEET_ID, SHEET_NAME + ':'.join([RANGE_START, RANGE_END]))
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\club_members.py", line 134, in get_members_from_spreadsheet
    rows = google_sheets.get_values(sheetId, value_range)
  File "C:\Users\MDL-Downstairs\Documents\ERPL-Bot-main\erplbot\sheets.py", line 33, in get_values
    result = request.execute()
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\MDL-Downstairs\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')

**Comment by ice-fly** [comment]
Temporarily fixed by deleting auth.bin and relogging. Might have had to do with testing...

**Comment by ice-fly** [comment]
Would Oauth2 with a service account work? 
[https://developers.google.com/identity/protocols/oauth2/service-account](https://developers.google.com/identity/protocols/oauth2/service-account)
